# Generated by Django 5.2 on 2026-01-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tester", "0003_starlinkkit_latitude_starlinkkit_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                    ("Active", "Active"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
